name: Main
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Clean And Install Packages
        run: npm ci
      - name: Build
        run:  ng build --output-path output --base-href /
      - name: Upload Static Pages
        uses: actions/upload-artifact@v2
        with:
          name: static-pages
          path: output

  deploy-github-pages:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Static Pages
        uses: actions/download-artifact@v2
        with:
          name: static-pages
          path: output
      - name: Deploy To The Github Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: output
